### ISSUE TITLE
`options.config` not used

### ISSUE THREAD

**Issue by nicholaschiasson** [jhinch/nginx-linter#2]
It seems like the the built in options always get used, even if passing in a path to a custom config.

**Comment by jhinch** [comment]
Hi. Thanks for the interest in this project. I am more than happy to receive a pull request to fix this. Must have been something I forgot to complete implementing when I built this.

**Comment by jhinch** [comment]
I was inspired to implement it myself. I have it is fixed in 0.5.0 which should be available on npm

**Comment by nicholaschiasson** [comment]
I was going to respond and say I would go for it, but that's awesome, thanks a lot! It seems to be working for me now! 👍
